In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import boxcox
from scipy.stats import yeojohnson


data=pd.read_excel("/content/practice_data.xlsx")
data.head()

,EmployeeID,gender,department,Days Present,Accuracy of Work,Meeting Project Deadlines,Task Completion Rates,Interpersonal Skills Rating,Decision-Making Skills Rating,Sales Revenue Generated,churned
0,1,Male,Sales,20,High,Yes,85,8,7,51638,No
1,2,Female,Marketing,22,Medium,Yes,90,7,6,97797,Yes
2,3,Male,Human Resources,25,High,No,80,9,8,95341,No
3,4,Male,Engineering,19,Low,Yes,75,6,5,91806,No
4,5,Female,Finance,23,Medium,Yes,85,7,7,64247,Yes

In [62]:
#boxcox transformation
from scipy.stats import shapiro,boxcox

column_name =data["Sales Revenue Generated"]

def boxcox_transformation (data,column_name):
  transformed_data, _ = boxcox(data[column_name])
  data[f'{column_name}_boxcox'] = transformed_data

  stat, p_value = shapiro(data[f'{column_name}_boxcox'])
  sns.kdeplot(data[f'{column_name}_boxcox'],fill='True')

  plt.show()

  print('P value: ', p_value)

In [63]:
#yeojohnson transformation

column_name = data["Sales Revenue Generated"]
def yeojohnson_transformation(data, column_name):
 transformed_data, _ = yeojohnson(data[column_name])
 data[f'{column_name}_yeojohnson'] = transformed_data
 stat, p_value = shapiro(data[f'{column_name}_yeojohnson'])
 kdeplot = sns.kdeplot(data[f'{column_name}_yeojohnson'])

 print(kdeplot)
 print('P value: ', p_value)

In [64]:
#one sample ttest
from scipy import stats


hypothesis_mean = 68

t_statistic, p_value = stats.ttest_1samp(data['Days Present'], hypothesis_mean)


print("T-statistic:", t_statistic)
print("P-value:", p_value)

alpha = 0.05


if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference between the average purchase amount and 68.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference between the average purchase amount and 68.")

T-statistic: -113.68705693077047
P-value: 4.271867321792959e-41
Reject the null hypothesis. There is a significant difference between the average purchase amount and 68.

In [65]:
#independent sample ttest
from scipy import stats
import pandas as pd


churned_customer = data[data['churned'] == 'Yes']['Sales Revenue Generated']
existing_customer =data[data['churned'] == 'No']['Sales Revenue Generated']


t_statistic, p_value = stats.ttest_ind(churned_customer, existing_customer, equal_var=False)  # Welch's t-test


print("T-statistic:", t_statistic)
print("P-value:", p_value)


alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. The group means are significantly different.")
else:
    print("Fail to reject the null hypothesis. No significant difference between group means.")

T-statistic: 0.6042785459584843
P-value: 0.5504064751595374
Fail to reject the null hypothesis. No significant difference between group means.

In [69]:
import pandas as pd
from scipy import stats


data = pd.DataFrame({
    "city": ["Chicago", "New York", "Houston", "Los_angeles"],
    "values": [4, 5, 7, 3]
})


groups = [group["values"].values for _, group in data.groupby("city")]


t_statistic, p_value = stats.f_oneway(*groups)


print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Interpret result
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis. At least one group mean is significantly different.")
else:
    print("Fail to reject the null hypothesis. No significant difference between group means.")

T-statistic: nan
P-value: nan
Fail to reject the null hypothesis. No significant difference between group means.

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:580: SmallSampleWarning: all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.
  if is_too_small(samples, kwds):
<ipython-input-69-3dfc635eebcc>:14: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  t_statistic, p_value = stats.f_oneway(*groups)